// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package kubernetes

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sRuntime "k8s.io/apimachinery/pkg/runtime"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Default StorageClass inside the tenant cluster. Remote-accessible LINSTOR classes are auto-propagated to the tenant under the same name.
	// +kubebuilder:default:="replicated"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
	// Worker nodes configuration map. When left empty, a default node group `md0` is emitted with `minReplicas: 0` and `roles: [ingress-nginx]` — the MachineDeployment renders but provisions no workers until an unschedulable Pod triggers the cluster-autoscaler (or an operator scales the group manually). Enabling `addons.ingressNginx.enabled: true` on a CR with default `nodeGroups: {}` therefore requires either supplying a nodeGroup with `roles: [ingress-nginx]` and `minReplicas >= 1`, or waiting for the autoscaler to bring up the default md0 in response to the ingress-nginx controller Pods becoming Pending. Provide your own groups to take full control — they are not merged with the default, so you may name and omit groups freely.
	// +kubebuilder:default:={}
	NodeGroups map[string]NodeGroup `json:"nodeGroups,omitempty"`
	// Kubernetes major.minor version to deploy
	// +kubebuilder:default:="v1.35"
	Version Version `json:"version"`
	// External hostname for Kubernetes cluster. Defaults to `<cluster-name>.<tenant-host>` if empty.
	// +kubebuilder:default:=""
	Host string `json:"host"`
	// Cluster addons configuration.
	// +kubebuilder:default:={}
	Addons Addons `json:"addons"`
	// Kubernetes control-plane configuration.
	// +kubebuilder:default:={}
	ControlPlane ControlPlane `json:"controlPlane"`
	// Optional image overrides for air-gapped or rate-limited registries.
	// +kubebuilder:default:={}
	Images Images `json:"images"`
	// Talos worker image configuration.
	// +kubebuilder:default:={}
	Talos Talos `json:"talos"`
	// MachineHealthCheck tuning for worker node groups.
	// +kubebuilder:default:={}
	NodeHealthCheck NodeHealthCheck `json:"nodeHealthCheck"`
	// OIDC authentication and per-user RBAC for the tenant kube-apiserver. See docs/oidc-tenant.md for the operator guide.
	// +kubebuilder:default:={}
	Oidc OIDC `json:"oidc"`
}

type APIServer struct {
	// Extra command-line flags appended to the tenant kube-apiserver, passed through to KamajiControlPlane `spec.apiServer.extraArgs`. For OIDC use `spec.oidc.mode` — this passthrough is the escape hatch for unrelated apiserver flags. When `spec.oidc.mode` is not `None` the chart renders `--requestheader-uid-headers=X-Remote-Uid` on `v1.32` and newer, plus `--feature-gates=RemoteRequestHeaderUID=true` on `v1.32` where that gate is still alpha, so the authenticated user's UID survives the hop to an aggregated apiserver; it skips its own copy when your entry already carries `X-Remote-Uid` or enables the gate, and fails the render with an actionable message when your entry and the chart cannot both be satisfied — a uid-headers list of yours omitting `X-Remote-Uid`, a `v1.32` `--feature-gates` entry that leaves `RemoteRequestHeaderUID` out (the chart needs that flag for itself there), or a `v1.33`-and-newer entry that sets `RemoteRequestHeaderUID=false`. Do NOT add legacy `--oidc-*` flags here when `spec.oidc.mode` is not `None`; the chart injects `--authentication-config` and the apiserver refuses to boot with both. Empty by default (no change to current behavior).
	// +kubebuilder:default:={}
	ExtraArgs []string `json:"extraArgs,omitempty"`
	// Extra volume mounts added to the tenant kube-apiserver container, passed through to KamajiControlPlane `spec.apiServer.extraVolumeMounts`. Each `name` must reference a volume declared in `extraVolumes`; the chart-managed talos secret volumes cannot be mounted. Each item is a core/v1 VolumeMount. Empty by default.
	// +kubebuilder:default:={}
	ExtraVolumeMounts []k8sRuntime.RawExtension `json:"extraVolumeMounts,omitempty"`
	// Extra volumes added to the control-plane Deployment, passed through to KamajiControlPlane `spec.deployment.extraVolumes`. Use to mount a ConfigMap or Secret holding an AuthenticationConfiguration file referenced by `extraArgs`. Each item is a core/v1 Volume, but because the control-plane pod runs on the management cluster only `configMap` and `secret` sources are allowed (host-reaching sources like `hostPath`/`csi` and token-projection via `projected` are rejected); each volume must have a unique, non-empty name and exactly one source. The names `talos-ca` and `talos-tls-cert` are reserved by the chart. Empty by default.
	// +kubebuilder:default:={}
	ExtraVolumes []k8sRuntime.RawExtension `json:"extraVolumes,omitempty"`
	// CPU and memory resources for API Server.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="c1.medium"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Addons struct {
	// Cert-manager addon.
	// +kubebuilder:default:={}
	CertManager CertManagerAddon `json:"certManager"`
	// Cilium CNI plugin.
	// +kubebuilder:default:={}
	Cilium CiliumAddon `json:"cilium"`
	// CoreDNS addon.
	// +kubebuilder:default:={}
	Coredns CoreDNSAddon `json:"coredns"`
	// FluxCD GitOps operator.
	// +kubebuilder:default:={}
	Fluxcd FluxCDAddon `json:"fluxcd"`
	// Gateway API addon.
	// +kubebuilder:default:={}
	GatewayAPI GatewayAPIAddon `json:"gatewayAPI"`
	// NVIDIA GPU Operator.
	// +kubebuilder:default:={}
	GpuOperator GPUOperatorAddon `json:"gpuOperator"`
	// HAMi GPU virtualization middleware.
	// +kubebuilder:default:={}
	Hami HAMiAddon `json:"hami"`
	// Ingress-NGINX controller.
	// +kubebuilder:default:={}
	IngressNginx IngressNginxAddon `json:"ingressNginx"`
	// Monitoring agents.
	// +kubebuilder:default:={}
	MonitoringAgents MonitoringAgentsAddon `json:"monitoringAgents"`
	// Hairpin-NAT fix for ingress-nginx with PROXY-protocol.
	// +kubebuilder:default:={}
	Ouroboros OuroborosAddon `json:"ouroboros"`
	// Velero backup/restore addon.
	// +kubebuilder:default:={}
	Velero VeleroAddon `json:"velero"`
	// Vertical Pod Autoscaler.
	// +kubebuilder:default:={}
	VerticalPodAutoscaler VerticalPodAutoscalerAddon `json:"verticalPodAutoscaler"`
}

type CertManagerAddon struct {
	// Enable cert-manager.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type CiliumAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type ControlPlane struct {
	// API Server configuration.
	// +kubebuilder:default:={}
	ApiServer APIServer `json:"apiServer"`
	// Controller Manager configuration.
	// +kubebuilder:default:={}
	ControllerManager ControllerManager `json:"controllerManager"`
	// Konnectivity configuration.
	// +kubebuilder:default:={}
	Konnectivity Konnectivity `json:"konnectivity"`
	// Number of control-plane replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Scheduler configuration.
	// +kubebuilder:default:={}
	Scheduler Scheduler `json:"scheduler"`
}

type ControllerManager struct {
	// CPU and memory resources for Controller Manager.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type CoreDNSAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type FluxCDAddon struct {
	// Enable FluxCD.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GPU struct {
	// Name of GPU, such as "nvidia.com/AD102GL_L40S".
	Name string `json:"name"`
}

type GPUOperatorAddon struct {
	// Enable GPU Operator.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type GatewayAPIAddon struct {
	// Enable Gateway API.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
}

type HAMiAddon struct {
	// Enable HAMi (requires GPU Operator).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Images struct {
	// Image used by the bootstrap-token tenant Job (kubectl). Empty falls back to images/kubectl.tag.
	// +kubebuilder:default:=""
	Kubectl string `json:"kubectl,omitempty"`
	// Image used by the talos-csr-signer sidecar in the Kamaji control plane. Empty falls back to images/talos-csr-signer.tag.
	// +kubebuilder:default:=""
	TalosCsrSigner string `json:"talosCsrSigner,omitempty"`
	// Image used by the wait-for-kubeconfig init container. Empty falls back to images/busybox.tag.
	// +kubebuilder:default:=""
	WaitForKubeconfig string `json:"waitForKubeconfig,omitempty"`
}

type IngressNginxAddon struct {
	// Enable the controller (requires nodes labeled `ingress-nginx`).
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Method to expose the controller. Allowed values: `Proxied`, `LoadBalancer`.
	// +kubebuilder:default:="Proxied"
	ExposeMethod IngressNginxExposeMethod `json:"exposeMethod"`
	// Domains routed to this tenant cluster when `exposeMethod` is `Proxied`.
	// +kubebuilder:default:={}
	Hosts []string `json:"hosts,omitempty"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Konnectivity struct {
	// Konnectivity Server configuration.
	// +kubebuilder:default:={}
	Server KonnectivityServer `json:"server"`
}

type KonnectivityServer struct {
	// CPU and memory resources for Konnectivity.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Kubelet struct {
	// Hard eviction threshold for memory (absolute like 200Mi or percentage like 7%).
	// +kubebuilder:default:="7%"
	EvictionHardMemory string `json:"evictionHardMemory,omitempty"`
	// Soft eviction threshold for memory (absolute like 1Gi or percentage like 10%).
	// +kubebuilder:default:="10%"
	EvictionSoftMemory string `json:"evictionSoftMemory,omitempty"`
	// CPU reserved for kubelet and container runtime. Auto-computed from instanceType if empty.
	KubeReservedCpu string `json:"kubeReservedCpu,omitempty"`
	// Memory reserved for kubelet and container runtime. Auto-computed from instanceType if empty.
	KubeReservedMemory string `json:"kubeReservedMemory,omitempty"`
	// CPU reserved for host OS. Auto-computed from instanceType if empty.
	SystemReservedCpu string `json:"systemReservedCpu,omitempty"`
	// Memory reserved for host OS. Auto-computed from instanceType if empty.
	SystemReservedMemory string `json:"systemReservedMemory,omitempty"`
}

type MonitoringAgentsAddon struct {
	// Enable monitoring agents.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type NodeGroup struct {
	// System disk size for the worker VM. Carries the Talos OS image (factory.talos.dev raw artifact streamed in by CDI), kubelet state, containerd image cache, and any local-path PVCs. Pre-Talos installs used a separate disk-kubelet PVC for kubelet/containerd state; on Talos this is consolidated onto the single system disk imaged from the factory artifact.
	// +kubebuilder:default:="20Gi"
	DiskSize resource.Quantity `json:"diskSize"`
	// List of GPUs to attach (NVIDIA driver requires at least 4 GiB RAM).
	Gpus []GPU `json:"gpus,omitempty"`
	// Virtual machine instance type.
	// +kubebuilder:default:="u1.medium"
	InstanceType string `json:"instanceType"`
	// Kubelet resource reservations for this node group.
	Kubelet Kubelet `json:"kubelet,omitempty"`
	// Maximum number of replicas.
	// +kubebuilder:default:=10
	MaxReplicas int `json:"maxReplicas"`
	// Per-group override for `nodeHealthCheck.maxUnhealthy`. When unset, the cluster-wide `nodeHealthCheck.maxUnhealthy` applies. Accepts a bare integer ("0", "1", ...) or an integer percentage ("0%", "50%").
	MaxUnhealthy string `json:"maxUnhealthy,omitempty"`
	// Minimum number of replicas.
	// +kubebuilder:default:=0
	MinReplicas int `json:"minReplicas"`
	// Per-group override for `nodeHealthCheck.nodeStartupTimeout`. When unset, the cluster-wide `nodeHealthCheck.nodeStartupTimeout` applies.
	NodeStartupTimeout string `json:"nodeStartupTimeout,omitempty"`
	// Explicit CPU and memory for each worker node, as an alternative to `instanceType` sizing. Optional: when omitted, the node is sized by `instanceType`. When both `cpu` and `memory` are set, they take precedence and `instanceType` is ignored for that node group (the instancetype is omitted from the VM, since KubeVirt cannot override an instancetype's CPU/memory). Set both `cpu` and `memory` together or neither; setting only one is rejected at render time.
	Resources Resources `json:"resources,omitempty"`
	// List of node roles.
	Roles []string `json:"roles,omitempty"`
	// StorageClass for worker node persistent disks. When empty, falls back to the application-level storageClass. Worker VMs live-migrate, so their disks need ReadWriteMany — the RWX access mode is supplied by the chosen StorageClass's CDI StorageProfile, not set on the DataVolume here — and linstor-csi rejects RWX volumes that are not on a DRBD-backed StorageClass, so the fallback targets the replicated/DRBD application storageClass rather than a possibly non-DRBD cluster default. NOTE: deliberately not marked immutable — the field is optional and undefaulted, so a strict `self == oldSelf` rule would block any future attempt to set it on an existing node group.
	StorageClass string `json:"storageClass,omitempty"`
}

type NodeHealthCheck struct {
	// Maximum number of unhealthy nodes tolerated per node group before remediation is paused. The MHC admission webhook accepts either a bare integer ("0", "1", ...) or a percentage ("0%", "50%"); bare numeric strings are rejected, so the safer default is to express the value as a percentage. Default "50%" leaves headroom for transient unhealthy nodes during the kubeadm-to-Talos rollover and slow first boots from factory.talos.dev. Drop to "0%" once the fleet is stable on Talos workers.
	// +kubebuilder:default:="50%"
	MaxUnhealthy string `json:"maxUnhealthy"`
	// Maximum time a Machine is allowed to spend reaching the Ready condition before it is remediated. Raise for slow first boots (Talos image fetch from factory.talos.dev or a busy storage class on the kubevirt-csi PVC populator).
	// +kubebuilder:default:="10m"
	NodeStartupTimeout string `json:"nodeStartupTimeout"`
}

type OIDC struct {
	// Tenant-supplied AuthenticationConfiguration; consumed only when `mode: CustomConfig`.
	// +kubebuilder:default:={}
	CustomConfig OIDCCustomConfig `json:"customConfig,omitempty"`
	// Identity mode. `None`: no OIDC, only the static admin kubeconfig works. `System`: trust the platform `cozy` realm via a per-cluster public client with audience binding; zero-config default. `CustomConfig`: trust a tenant-supplied issuer directly (BYO); `cozy` is not in the path.
	// +kubebuilder:default:="None"
	Mode OIDCMode `json:"mode"`
	// Users granted access to the tenant cluster; each entry produces one ClusterRoleBinding inside the tenant cluster. Works for both `System` and `CustomConfig` modes.
	// +kubebuilder:default:={}
	Users []OIDCUser `json:"users,omitempty"`
}

type OIDCCustomConfig struct {
	// Inline AuthenticationConfiguration YAML (`apiserver.config.k8s.io/v1beta1`). The chart writes the value verbatim into a Secret mounted at `/etc/kubernetes/authentication-config/config.yaml` on the kube-apiserver. Mutually exclusive with `secretRef.name`.
	// +kubebuilder:default:=""
	Config string `json:"config,omitempty"`
	// Reference to an existing Secret in the tenant namespace carrying the `AuthenticationConfiguration`.
	// +kubebuilder:default:={}
	SecretRef OIDCSecretRef `json:"secretRef,omitempty"`
}

type OIDCSecretRef struct {
	// Name of an existing Secret in the tenant (release) namespace whose `config.yaml` key holds an `apiserver.config.k8s.io/v1beta1` `AuthenticationConfiguration`. Mutually exclusive with `customConfig.config`.
	// +kubebuilder:default:=""
	Name string `json:"name,omitempty"`
}

type OIDCUser struct {
	// Email address matched against the `email` claim from the issuer. Used verbatim as the `User:` subject in the ClusterRoleBinding inside the tenant cluster. The `email` claim is a built-in OIDC scope requested explicitly by the chart-generated `kubectl oidc-login` kubeconfig; every conformant OIDC provider (cozy realm included) emits it.
	Email string `json:"email"`
	// Role to bind: `admin` maps to `ClusterRole/cluster-admin`, `view` maps to `ClusterRole/view`.
	Role OIDCRole `json:"role"`
}

type OuroborosAddon struct {
	// Enable ouroboros. Requires addons.ingressNginx.enabled (chart-render fail otherwise). Only useful when PROXY-protocol is wired on the tenant ingress-nginx via valuesOverride.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides. Operator-key wins over cozystack defaults.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type Resources struct {
	// CPU available.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type Scheduler struct {
	// CPU and memory resources for Scheduler.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Preset if `resources` omitted.
	// +kubebuilder:default:="t1.micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
}

type Talos struct {
	// Base URL of the Talos Image Factory that serves the worker OS disk image (the `openstack-amd64.raw.xz` raw artifact streamed in by CDI over HTTP). Defaults to the public factory. Point at a self-hosted Image Factory, a caching mirror, or an internal HTTP file server for air-gapped, rate-limited, or flaky-egress environments. No trailing slash.
	// +kubebuilder:default:="https://factory.talos.dev"
	ImageFactoryURL string `json:"imageFactoryURL"`
	// OCI repository prefix for the Talos installer image used by the in-guest `talos-reconcile` upgrade Job. Resolved as `<installerRepository>/<schematicID>:<version>`. Defaults to the public factory's installer path. Override for air-gapped or mirrored registries. No trailing slash.
	// +kubebuilder:default:="factory.talos.dev/installer"
	InstallerRepository string `json:"installerRepository"`
	// Talos image-factory schematic ID. Defaults to the cozystack-tested vanilla schematic. Operators using custom schematics (system extensions, kernel args) override here.
	// +kubebuilder:default:="ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515"
	SchematicID string `json:"schematicID"`
	// Talos release used for worker OS image and installer. Must satisfy the chart's Talos<->Kubernetes support matrix against the chosen `version`.
	// +kubebuilder:default:="v1.13.6"
	Version string `json:"version"`
}

type VeleroAddon struct {
	// Enable Velero.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

type VerticalPodAutoscalerAddon struct {
	// Custom Helm values overrides.
	// +kubebuilder:default:={}
	ValuesOverride k8sRuntime.RawExtension `json:"valuesOverride"`
}

// +kubebuilder:validation:Enum="Proxied";"LoadBalancer"
type IngressNginxExposeMethod string

// +kubebuilder:validation:Enum="None";"System";"CustomConfig"
type OIDCMode string

// +kubebuilder:validation:Enum="admin";"view"
type OIDCRole string

// +kubebuilder:validation:Enum="t1.nano";"t1.micro";"t1.small";"t1.medium";"t1.large";"t1.xlarge";"t1.2xlarge";"t1.4xlarge";"c1.nano";"c1.micro";"c1.small";"c1.medium";"c1.large";"c1.xlarge";"c1.2xlarge";"c1.4xlarge";"s1.nano";"s1.micro";"s1.small";"s1.medium";"s1.large";"s1.xlarge";"s1.2xlarge";"s1.4xlarge";"u1.nano";"u1.micro";"u1.small";"u1.medium";"u1.large";"u1.xlarge";"u1.2xlarge";"u1.4xlarge";"m1.nano";"m1.micro";"m1.small";"m1.medium";"m1.large";"m1.xlarge";"m1.2xlarge";"m1.4xlarge";"nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v1.35";"v1.34";"v1.33";"v1.32";"v1.31"
type Version string
