#!/usr/bin/env bats
# Guards against committing an image reference whose digest is a placeholder.
#
# A reference like `<repo>:<tag>@sha256:000…0` is worse than a missing one: it is
# well-formed, so `required` and every schema check pass, and it renders into a
# DataVolume / Deployment that then fails to pull forever. The failure surfaces at
# runtime as a stuck import rather than at render as an error, and
# hack/nightly-mirror.sh skips it silently instead of failing, because its
# ownership filter matches the build-registry host and a not-yet-published
# reference usually still carries the public one. See docs/agents/image-refs.md:
# "Every first-party reference is tag+digest… A bare tag with no digest is not
# reproducible and must not be committed" — an unresolvable digest is the same
# defect wearing a valid shape.
#
# This is deliberately shape-agnostic: it greps the tree rather than asking
# hack/lib/image-refs.sh where references live, so it also catches a reference in
# a file the enumeration has never heard of (the failure mode that shipped a
# half-promoted release — see hack/promote-rewrite-tags_test.bats).
#
# Harness note: the CI path is hack/cozytest.sh, NOT real bats. There is no `run`,
# `$status`, `$output`, `skip`, or setup()/teardown(); each test runs as a shell
# function under `set -eu -x`, so a non-zero exit is the failure. Paths are
# repo-root-relative — BATS_TEST_DIRNAME is unset and would abort the whole suite
# under `set -u`.
#
# Run with: hack/cozytest.sh hack/image-refs-no-placeholder.bats

@test "no committed image reference carries a placeholder (all-zero) digest" {
  # -I skips binaries. charts/ is excluded because vendored upstream chart values
  # are regenerated by `make update` and are not ours to gate. tests/ is excluded
  # because helm-unittest fixtures legitimately use an all-zero digest as sample
  # data against a fake registry (see
  # packages/apps/kubernetes/tests/admin_kubeconfig_wait_test.yaml) — that is test
  # input, not a reference this repo ships. No shipped reference lives under
  # tests/, so this is not a blind spot.
  hits="$(grep -rIlE '@sha256:0{64}' packages/ --exclude-dir=charts --exclude-dir=tests || true)"

  if [ -n "$hits" ]; then
    echo "Placeholder image digest committed in:"
    echo "$hits" | sed 's/^/  /'
    echo ""
    echo "An all-zero digest is a reference that resolves nowhere while looking"
    echo "like a valid pin. Stamp the real digest from the image build that"
    echo "published the artifact before merging (for the VyOS appliance that is"
    echo "the build-vyos CI job, which writes"
    echo "packages/apps/site-router/images/vyos-router-disk.tag)."
    exit 1
  fi
}
