// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package siterouter

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Site-to-site tunnel configuration.
	// +kubebuilder:default:={}
	Tunnel Tunnel `json:"tunnel"`
	// Remote peer this router builds a tunnel to.
	// +kubebuilder:default:={}
	Peer Peer `json:"peer"`
	// Remote networks reachable over the tunnel. Must be disjoint from cluster pod/service/join networks, live node addresses, and allocated LoadBalancer/external service addresses (validated at admission and by the controller).
	// +kubebuilder:default:={}
	RemoteCIDRs []string `json:"remoteCIDRs,omitempty"`
	// Optional extra static routes programmed on the router.
	// +kubebuilder:default:={}
	StaticRoutes []StaticRoute `json:"staticRoutes,omitempty"`
	// Optional BGP peering over the tunnel. Disabled by default.
	// +kubebuilder:default:={}
	Bgp BGP `json:"bgp"`
	// Platform-owned network security guards for the gateway VM.
	// +kubebuilder:default:={}
	Security Security `json:"security"`
	// Explicit CPU and memory sizing for the router VM.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources"`
	// Source CIDR allowed to reach the VyOS management API (HTTPS 443) through the first-boot firewall. This value and the controller's --management-cidr flag (T05/T06) must agree: both default to the cluster pod CIDR (10.244.0.0/16, the kube-ovn default) and must be kept consistent. On a cluster with a non-default `networking.podCIDR`, set this (and the controller's managementCidr) to that pod CIDR, or the firewall will reject the real controller source. An empty value requires `allowOpenManagement=true` (fail-closed). Constrained to a strict IPv4 CIDR (or empty) so a tenant value cannot inject arbitrary text into the VyOS first-boot config.
	// +kubebuilder:default:="10.244.0.0/16"
	// +kubebuilder:validation:Pattern="^(((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])/(3[0-2]|[12]?[0-9]))?$"
	ManagementCIDR string `json:"managementCIDR"`
	// Permit an empty `managementCIDR`, leaving the VyOS management API unrestricted (no first-boot firewall). Fail-closed by default: an empty `managementCIDR` with this false aborts rendering.
	// +kubebuilder:default:=false
	AllowOpenManagement bool `json:"allowOpenManagement"`
	// Opaque seed mixed into the VM firmware UUID. Change it to force a first-boot cloud-init re-run; clear it to preserve an existing VM's UUID across re-renders.
	// +kubebuilder:default:=""
	CloudInitSeed string `json:"cloudInitSeed,omitempty"`
}

type BGP struct {
	// Enable BGP peering.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Local autonomous system number. Required when `enabled` is true; must be a valid ASN (1..4294967295).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4.294967295e+09
	LocalASN int `json:"localASN,omitempty"`
	// BGP neighbors to peer with.
	Neighbors []BGPNeighbor `json:"neighbors,omitempty"`
}

type BGPNeighbor struct {
	// Neighbor IP address.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"
	Address string `json:"address"`
	// Remote autonomous system number of the neighbor. Must be a valid ASN (1..4294967295).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4.294967295e+09
	RemoteASN int `json:"remoteASN"`
}

type Peer struct {
	// Public address (IP or hostname) of the remote peer. Responder model: the remote peer dials in.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:Pattern="^[A-Za-z0-9.:-]*$"
	Address string `json:"address"`
	// IPsec authentication material for the tunnel.
	// +kubebuilder:default:={}
	Auth PeerAuth `json:"auth,omitempty"`
}

type PeerAuth struct {
	// Name of an existing Secret in the tenant namespace holding the pre-shared key (key `psk`). Takes precedence over `psk` when set.
	ExistingSecret string `json:"existingSecret,omitempty"`
	// IPsec pre-shared key. Autogenerated and stored in a Secret when omitted. Mutually exclusive with `existingSecret`.
	Psk string `json:"psk,omitempty"`
}

type Resources struct {
	// CPU topology cores allocated to the router VM. Whole cores only; a fractional quantity (e.g. "1500m", "0.5") is rejected at admission rather than silently truncated to zero. At least one core: `cpu: 0` and negative values otherwise pass admission and render an unusable KubeVirt CPU topology.
	// +kubebuilder:default:=2
	// +kubebuilder:validation:Minimum=1
	Cpu int `json:"cpu"`
	// Memory (RAM) allocated to the router VM.
	// +kubebuilder:default:="2Gi"
	Memory resource.Quantity `json:"memory"`
}

type Security struct {
	// Extra destination CIDRs the gateway is denied egress to, on top of the built-in link-local `169.254.0.0/16` deny (which always applies and covers the cloud metadata endpoint `169.254.169.254`). Use for management or node ranges that do not overlap tenant workloads; do NOT list the cluster pod/service/join ranges (the gateway must reach tenant workloads). Empty by default.
	// +kubebuilder:default:={}
	EgressDenyCIDRs []string `json:"egressDenyCIDRs,omitempty"`
}

type StaticRoute struct {
	// Destination network in CIDR notation.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])/(3[0-2]|[12]?[0-9])$"
	Destination string `json:"destination"`
	// Next-hop IP address for the destination.
	// +kubebuilder:validation:Pattern="^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"
	NextHop string `json:"nextHop"`
}

type Tunnel struct {
	// Tunnel protocol used to connect to the remote peer.
	// +kubebuilder:default:="ipsec"
	Type TunnelType `json:"type"`
}

// +kubebuilder:validation:Enum="ipsec"
type TunnelType string
